# Generated by Django 5.1 on 2024-08-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageFrnds', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10),
        ),
    ]
