# Generated by Django 5.1 on 2024-08-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageFrnds', '0002_alter_friendrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
